# Generated by Django 5.1.4 on 2024-12-13 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('avg', models.IntegerField()),
                ('adress', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
