# Generated by Django 5.1.4 on 2024-12-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_remove_student_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255)),
                ('person_mobile_no', models.CharField(max_length=15)),
                ('adhar_no', models.CharField(max_length=12)),
                ('adhar_front', models.ImageField(blank=True, null=True, upload_to='uploads/adhar/')),
                ('adhar_back', models.ImageField(blank=True, null=True, upload_to='uploads/adhar/')),
                ('institute_reg_copy', models.ImageField(blank=True, null=True, upload_to='uploads/institute/')),
                ('institute_name', models.CharField(max_length=255)),
                ('institute_govt_reg_no', models.CharField(max_length=255)),
                ('institute_website', models.URLField()),
                ('password', models.CharField(max_length=255)),
                ('confirm_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
