# Generated by Django 5.1.4 on 2024-12-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_registration_delete_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='adhar_no',
            new_name='aadhar_no',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='adhar_back',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='adhar_front',
        ),
        migrations.AddField(
            model_name='registration',
            name='aadhar_back',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/aadhar/'),
        ),
        migrations.AddField(
            model_name='registration',
            name='aadhar_front',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/aadhar/'),
        ),
    ]
